### ISSUE TITLE
Some where bugs

### ISSUE THREAD

**Issue by YomaDan** [JamesMGreene/nedb-session-store#3]
Its correct situation, on every client reload page session file injects many repeats records with non unical id.
Example:

{"_id":"B9kOdZa6jSyb8D6YxlT86dFZbyFiVQRi","session":{"cookie":{"originalMaxAge":null,"expires":null,"httpOnly":true,"path":"/"}},"expiresAt":{"$$date":1530012101535},"createdAt":{"$$date":1528802482953},"updatedAt":{"$$date":1528802591344}}
{"_id":"B9kOdZa6jSyb8D6YxlT86dFZbyFiVQRi","session":{"cookie":{"originalMaxAge":null,"expires":null,"httpOnly":true,"path":"/"}},"expiresAt":{"$$date":1530012272929},"createdAt":{"$$date":1528802482953},"updatedAt":{"$$date":1528802672941}}
{"_id":"B9kOdZa6jSyb8D6YxlT86dFZbyFiVQRi","session":{"cookie":{"originalMaxAge":null,"expires":null,"httpOnly":true,"path":"/"}},"expiresAt":{"$$date":1530012272972},"createdAt":{"$$date":1528802482953},"updatedAt":{"$$date":1528802672973}}
{"_id":"B9kOdZa6jSyb8D6YxlT86dFZbyFiVQRi","session":{"cookie":{"originalMaxAge":null,"expires":null,"httpOnly":true,"path":"/"}},"expiresAt":{"$$date":1530012272999},"createdAt":{"$$date":1528802482953},"updatedAt":{"$$date":1528802673000}}
{"_id":"B9kOdZa6jSyb8D6YxlT86dFZbyFiVQRi","session":{"cookie":{"originalMaxAge":null,"expires":null,"httpOnly":true,"path":"/"}},"expiresAt":{"$$date":1530012272999},"createdAt":{"$$date":1528802482953},"updatedAt":{"$$date":1528802673030}}
{"_id":"B9kOdZa6jSyb8D6YxlT86dFZbyFiVQRi","session":{"cookie":{"originalMaxAge":null,"expires":null,"httpOnly":true,"path":"/"}},"expiresAt":{"$$date":1530012273000},"createdAt":{"$$date":1528802482953},"updatedAt":{"$$date":1528802673054}}
{"_id":"B9kOdZa6jSyb8D6YxlT86dFZbyFiVQRi","session":{"cookie":{"originalMaxAge":null,"expires":null,"httpOnly":true,"path":"/"}},"expiresAt":{"$$date":1530012273554},"createdAt":{"$$date":1528802482953},"updatedAt":{"$$date":1528802673555}}
{"_id":"B9kOdZa6jSyb8D6YxlT86dFZbyFiVQRi","session":{"cookie":{"originalMaxAge":null,"expires":null,"httpOnly":true,"path":"/"}},"expiresAt":{"$$date":1530012273554},"createdAt":{"$$date":1528802482953},"updatedAt":{"$$date":1528802673557}}
{"_id":"B9kOdZa6jSyb8D6YxlT86dFZbyFiVQRi","session":{"cookie":{"originalMaxAge":null,"expires":null,"httpOnly":true,"path":"/"}},"expiresAt":{"$$date":1530012278025},"createdAt":{"$$date":1528802482953},"updatedAt":{"$$date":1528802678027}}
{"_id":"B9kOdZa6jSyb8D6YxlT86dFZbyFiVQRi","session":{"cookie":{"originalMaxAge":null,"expires":null,"httpOnly":true,"path":"/"}},"expiresAt":{"$$date":1530012278069},"createdAt":{"$$date":1528802482953},"updatedAt":{"$$date":1528802678069}}
{"_id":"B9kOdZa6jSyb8D6YxlT86dFZbyFiVQRi","session":{"cookie":{"originalMaxAge":null,"expires":null,"httpOnly":true,"path":"/"}},"expiresAt":{"$$date":1530012278069},"createdAt":{"$$date":1528802482953},"updatedAt":{"$$date":1528802678073}}
{"_id":"B9kOdZa6jSyb8D6YxlT86dFZbyFiVQRi","session":{"cookie":{"originalMaxAge":null,"expires":null,"httpOnly":true,"path":"/"}},"expiresAt":{"$$date":1530012278069},"createdAt":{"$$date":1528802482953},"updatedAt":{"$$date":1528802678076}}
{"_id":"B9kOdZa6jSyb8D6YxlT86dFZbyFiVQRi","session":{"cookie":{"originalMaxAge":null,"expires":null,"httpOnly":true,"path":"/"}},"expiresAt":{"$$date":1530012278069},"createdAt":{"$$date":1528802482953},"updatedAt":{"$$date":1528802678079}}
{"_id":"B9kOdZa6jSyb8D6YxlT86dFZbyFiVQRi","session":{"cookie":{"originalMaxAge":null,"expires":null,"httpOnly":true,"path":"/"}},"expiresAt":{"$$date":1530012278596},"createdAt":{"$$date":1528802482953},"updatedAt":{"$$date":1528802678596}}
{"_id":"B9kOdZa6jSyb8D6YxlT86dFZbyFiVQRi","session":{"cookie":{"originalMaxAge":null,"expires":null,"httpOnly":true,"path":"/"}},"expiresAt":{"$$date":1530012278596},"createdAt":{"$$date":1528802482953},"updatedAt":{"$$date":1528802678601}}
{"_id":"B9kOdZa6jSyb8D6YxlT86dFZbyFiVQRi","session":{"cookie":{"originalMaxAge":null,"expires":null,"httpOnly":true,"path":"/"}},"expiresAt":{"$$date":1530012281177},"createdAt":{"$$date":1528802482953},"updatedAt":{"$$date":1528802681178}}
{"_id":"B9kOdZa6jSyb8D6YxlT86dFZbyFiVQRi","session":{"cookie":{"originalMaxAge":null,"expires":null,"httpOnly":true,"path":"/"}},"expiresAt":{"$$date":1530012281228},"createdAt":{"$$date":1528802482953},"updatedAt":{"$$date":1528802681228}}
{"_id":"B9kOdZa6jSyb8D6YxlT86dFZbyFiVQRi","session":{"cookie":{"originalMaxAge":null,"expires":null,"httpOnly":true,"path":"/"}},"expiresAt":{"$$date":1530012281228},"createdAt":{"$$date":1528802482953},"updatedAt":{"$$date":1528802681231}}
{"_id":"B9kOdZa6jSyb8D6YxlT86dFZbyFiVQRi","session":{"cookie":{"originalMaxAge":null,"expires":null,"httpOnly":true,"path":"/"}},"expiresAt":{"$$date":1530012281228},"createdAt":{"$$date":1528802482953},"updatedAt":{"$$date":1528802681252}}
{"_id":"B9kOdZa6jSyb8D6YxlT86dFZbyFiVQRi","session":{"cookie":{"originalMaxAge":null,"expires":null,"httpOnly":true,"path":"/"}},"expiresAt":{"$$date":1530012281228},"createdAt":{"$$date":1528802482953},"updatedAt":{"$$date":1528802681280}}
{"_id":"B9kOdZa6jSyb8D6YxlT86dFZbyFiVQRi","session":{"cookie":{"originalMaxAge":null,"expires":null,"httpOnly":true,"path":"/"}},"expiresAt":{"$$date":1530012281896},"createdAt":{"$$date":1528802482953},"updatedAt":{"$$date":1528802681896}}
{"_id":"B9kOdZa6jSyb8D6YxlT86dFZbyFiVQRi","session":{"cookie":{"originalMaxAge":null,"expires":null,"httpOnly":true,"path":"/"}},"expiresAt":{"$$date":1530012281896},"createdAt":{"$$date":1528802482953},"updatedAt":{"$$date":1528802681901}}
{"_id":"B9kOdZa6jSyb8D6YxlT86dFZbyFiVQRi","session":{"cookie":{"originalMaxAge":null,"expires":null,"httpOnly":true,"path":"/"}},"expiresAt":{"$$date":1530012285560},"createdAt":{"$$date":1528802482953},"updatedAt":{"$$date":1528802685561}}
{"_id":"B9kOdZa6jSyb8D6YxlT86dFZbyFiVQRi","session":{"cookie":{"originalMaxAge":null,"expires":null,"httpOnly":true,"path":"/"}},"expiresAt":{"$$date":1530012285620},"createdAt":{"$$date":1528802482953},"updatedAt":{"$$date":1528802685621}}
{"_id":"B9kOdZa6jSyb8D6YxlT86dFZbyFiVQRi","session":{"cookie":{"originalMaxAge":null,"expires":null,"httpOnly":true,"path":"/"}},"expiresAt":{"$$date":1530012285621},"createdAt":{"$$date":1528802482953},"updatedAt":{"$$date":1528802685641}}
{"_id":"B9kOdZa6jSyb8D6YxlT86dFZbyFiVQRi","session":{"cookie":{"originalMaxAge":null,"expires":null,"httpOnly":true,"path":"/"}},"expiresAt":{"$$date":1530012285658},"createdAt":{"$$date":1528802482953},"updatedAt":{"$$date":1528802685658}}
{"_id":"B9kOdZa6jSyb8D6YxlT86dFZbyFiVQRi","session":{"cookie":{"originalMaxAge":null,"expires":null,"httpOnly":true,"path":"/"}},"expiresAt":{"$$date":1530012285658},"createdAt":{"$$date":1528802482953},"updatedAt":{"$$date":1528802685668}}
{"_id":"B9kOdZa6jSyb8D6YxlT86dFZbyFiVQRi","session":{"cookie":{"originalMaxAge":null,"expires":null,"httpOnly":true,"path":"/"}},"expiresAt":{"$$date":1530012286346},"createdAt":{"$$date":1528802482953},"updatedAt":{"$$date":1528802686346}}
{"_id":"B9kOdZa6jSyb8D6YxlT86dFZbyFiVQRi","session":{"cookie":{"originalMaxAge":null,"expires":null,"httpOnly":true,"path":"/"}},"expiresAt":{"$$date":1530012286346},"createdAt":{"$$date":1528802482953},"updatedAt":{"$$date":1528802686348}}

**Comment by JamesMGreene** [comment]
That is actually standard and expected NeDB behavior. Please read the section of the NeDB documentation called [Persistence](https://github.com/louischatriot/nedb/blob/master/README.md#persistence) for further explanation.

Long story short: those "duplicate" lines will go away the next time the NeDB Datastore is compacted.
